name: Continuous integration (frontend)

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    - name: Run react tests
      run: |
        cd frontend
        npm test
    - name: Check prettier conformance
      if: success() || failure()
      run: |
        cd frontend
        npx prettier --check .
